site_name: Essential skills for reproducible research computing
pages:
    - Home: index.md
    - UNIX Command Line:
        - Navigation: nix/navigation.md
        - File Creation and Editing: nix/file_handling.md
        - Redirection: nix/redirection.md
        - Piping: nix/pipes.md
        - man and less: nix/man_and_less.md
        - Uber exercise: nix/uber.md
    - (I)Python: 
        - Python: python.md
    - git:
        - git: git/git.md
        - GitHub:
            - push and pull: git/github1.md
            - merging: git/merge.md
            - conflicts: git/conflicts.md
    - Numba:
        - Profiling: numba/1.md
        - Intro to JIT: numba/2.md
        - Numba Internals: numba/3.md
        - CFD Intro: numba/4.md
        - Cavity Flow: numba/5.md
        - vectorize: numba/6.md

extra_javascript: 
    - http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
    - mdx_math
theme: readthedocs
docs_dir: docs
site_dir: _site
